### ISSUE TITLE
Digest FAIR Principles

### ISSUE THREAD

**Issue by slarson** [openworm/OpenData#1]
Article here:

http://www.pubmedcentral.nih.gov/articlerender.fcgi?artid=4792175&tool=pmcentrez&rendertype=abstract

Goal: Come up with 5-7 practical bullet points for what we could do this summer to make our data sets follow FAIR principles.  Incorporate into project proposal plan.

**Comment by EST09** [comment]
Paper summary and suggestions:
https://docs.google.com/presentation/d/1lQ1eeQ8ltNY06iEBWDzHDvWaZ1nDmZexYTMpHBj4toc/edit?usp=sharing

Incorporate into Proposal after discussion

**Comment by slarson** [comment]
Nice summary!
