### ISSUE TITLE
Read paper about making a ML model of worm movement

### ISSUE THREAD

**Issue by slarson** [openworm/OpenData#5]
Purpose is to understand how the data were prepared to feed into a machine learning model:

https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnx3d25pcDIwMTd8Z3g6N2EyODc2YWZmOGYyZWY4MQ

Don't worry about the details of the algorithms.  Focus on:

* What the underlying data ARE
* How the data were grouped to build the model

**Comment by EST09** [comment]
Read. Think this is the precursor to Tierspy 16. Should double check on this.
