### ISSUE TITLE
Download and have a look at the first candidate standard worm dataset

### ISSUE THREAD

**Issue by slarson** [openworm/OpenData#6]
- [x] Download and orient to the contents: https://www.dropbox.com/sh/aansr9pv1fl3s8p/AACSmLX7I525VjK9apoduAzRa?dl=0
 - [x] Experiment opening data set as a [Stack in ImageJ](https://imagej.nih.gov/ij/docs/guide/146-8.html)
 - [x] Do some google searching to see if there are imagej based tools to do 3D spatial mapping with a Stack

**Comment by mwatts15** [comment]
@slarson , can you provide some citation info on this data? We need a dataset for openworm/PyOpenWorm#408, and I would use something from the movement database, but I think it would be interesting to work with common data sets across projects this summer.

**Comment by slarson** [comment]
@mwatts15 -- No citation yet for this data as it is a purely experimental data set at the moment!  Citation would come later.

**Comment by EST09** [comment]
This paper seems to describe what we want to do?
A 3D digital atlas of C. elegans and its application to single-cell analyses 
Fuhui Long, Hanchuan Peng, Xiao Liu, Stuart K Kim & Eugene Myers
https://www.nature.com/articles/nmeth.1366

**Comment by slarson** [comment]
[A 3D digital atlas of C. elegans and its application to single-cell analyses. - 2009.pdf](https://github.com/openworm/OpenData/files/3322462/A.3D.digital.atlas.of.C.elegans.and.its.application.to.single-cell.analyses.-.2009.pdf)
