### ISSUE TITLE
Find references on different dynamical types of c. elegans neurons

### ISSUE THREAD

**Issue by slarson** [openworm/OpenData#7]
This would be important to have a sense for the different dynamical modes that c. elegans neurons take

**Comment by EST09** [comment]
Leifer Dataset: https://osf.io/mw5zs/
Will update as get more into project

**Comment by EST09** [comment]
Papers citing Leifer calcium imaging paper: [Whole-brain calcium imaging with cellular resolution in freely behaving Caenorhabditis elegans](https://www.pnas.org/content/pnas/113/8/E1074.full.pdf) - 
https://docs.google.com/spreadsheets/d/11Q5nMHtLhz6IMaQajONt3ZOn1HuYLbRf7l-ZkxI8sDk/edit?usp=sharing
