### ISSUE TITLE
Determine how to operationalize FAIR principles for the data sets we identify

### ISSUE THREAD

**Issue by slarson** [openworm/OpenData#8]
Let's write out a set of 5-10 steps for actions to take specifically to make data FAIR.  Let's start with the movement data specifically.  Let's do this before we take an action so that we can begin to define our project.

**Comment by EST09** [comment]
Ongoing. refer back to: https://docs.google.com/presentation/d/1lQ1eeQ8ltNY06iEBWDzHDvWaZ1nDmZexYTMpHBj4toc/edit?usp=sharing

**Comment by EST09** [comment]
A start to defining the categories for the movement data: 
https://docs.google.com/spreadsheets/d/1xKMq04pUpB_us-xPQRv13zjqQ6DpFx4f6ALYSundV2A/edit?usp=sharing
Based on what is already in Zenodo: 
https://about.zenodo.org/principles/
using this example: https://zenodo.org/record/1034929#.XQdCD7xKg2x
and the detail on the FAIR principles available here: 
https://www.go-fair.org/fair-principles/

**Comment by EST09** [comment]
Finished integration of WCON, POW and FAIR:
https://docs.google.com/spreadsheets/d/1g1tP04rkXD4vkIwbSrilKUxc8uyjQWRGiCj0RT_E8hg/edit?usp=sharing
